### ISSUE TITLE
"This isn't the best way"

### ISSUE THREAD

**Issue by snorfalorpagus** [galexrt/presentation-gitlab-k8s#1]
Thanks for making this available. In the README it says:

> INFO This isn't the best way to deploy application Docker images to K8s, this is more of an example how simple it can be.

Is there a discussion somewhere on the limitations of the approach taken? Why isn't it the best?

**Comment by galexrt** [comment]
Limitations of this repo / example:
* Uses `sed` for "templating", Helm would be much better.
  * GitLab Auto DevOps provides what this "manual" example does but with one click as far as I have been told. Personal note: This repo is a "perfect" example to show what happens in a nutshell from my perspective.
* Side effect for projects that are using the "same" CI / CD code (e.g., `.gitlab-ci.yml`) is if you change one thing you need to open a PR in each projects repo.
  * I have heard about projects that allow to sync these files / tools across multiple projects though can't remember one out of my mind right now.

These are the ones that come to my mind besides, that some code / manifests parts are feeling a bit rought ("style wise").

There isn't / wasn't really a discussion going on, but feel free to discuss here.

**Comment by snorfalorpagus** [comment]
Thanks! That's helpful.
